"""empty message

Revision ID: 03caab2d53d7
Revises: c5bbf03e3f10
Create Date: 2018-12-09 14:49:50.005440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '03caab2d53d7'
down_revision = 'c5bbf03e3f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    seat_type = postgresql.ENUM('Coach', 'First', name='seat_type')
    seat_type.create(op.get_bind())
    op.add_column('gsa_flight', sa.Column('seat_class', sa.Enum('Coach', 'First', name='seat_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gsa_flight', 'seat_class')
    seat_type = postgresql.ENUM('Coach', 'First', name='seat_type')
    seat_type.drop(op.get_bind())
    # ### end Alembic commands ###
