"""empty message

Revision ID: 25735bde410d
Revises: c99dd5cc3d61
Create Date: 2019-02-02 13:29:58.874081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25735bde410d'
down_revision = 'c99dd5cc3d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airline', 'slug')
    op.drop_column('airport', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airport', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('airline', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
