"""empty message

Revision ID: 38103c03dbe1
Revises: f004af0e2654
Create Date: 2018-12-09 13:57:24.324435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38103c03dbe1'
down_revision = 'f004af0e2654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gsa_flight_destination_id_fkey', 'gsa_flight', type_='foreignkey')
    op.drop_constraint('gsa_flight_origin_id_fkey', 'gsa_flight', type_='foreignkey')
    op.drop_constraint('gsa_flight_airline_id_fkey', 'gsa_flight', type_='foreignkey')
    op.drop_column('gsa_flight', 'fare_type')
    op.drop_column('gsa_flight', 'airline_id')
    op.drop_column('gsa_flight', 'flight_class')
    op.drop_column('gsa_flight', 'reservation_date')
    op.drop_column('gsa_flight', 'online')
    op.drop_column('gsa_flight', 'trip_date')
    op.drop_column('gsa_flight', 'tax')
    op.drop_column('gsa_flight', 'origin_id')
    op.drop_column('gsa_flight', 'invoice')
    op.drop_column('gsa_flight', 'destination_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsa_flight', sa.Column('destination_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gsa_flight', sa.Column('invoice', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('gsa_flight', sa.Column('origin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gsa_flight', sa.Column('tax', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('gsa_flight', sa.Column('trip_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('gsa_flight', sa.Column('online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('gsa_flight', sa.Column('reservation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('gsa_flight', sa.Column('flight_class', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('gsa_flight', sa.Column('airline_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gsa_flight', sa.Column('fare_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('gsa_flight_airline_id_fkey', 'gsa_flight', 'airline', ['airline_id'], ['id'])
    op.create_foreign_key('gsa_flight_origin_id_fkey', 'gsa_flight', 'airport', ['origin_id'], ['id'])
    op.create_foreign_key('gsa_flight_destination_id_fkey', 'gsa_flight', 'airport', ['destination_id'], ['id'])
    # ### end Alembic commands ###
