"""empty message

Revision ID: 403dd57665d2
Revises: 03caab2d53d7
Create Date: 2018-12-09 16:09:49.213474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '403dd57665d2'
down_revision = '03caab2d53d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gsa_flight', 'seat_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsa_flight', sa.Column('seat_class', postgresql.ENUM('Coach', 'First', name='seat_type'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
