"""empty message

Revision ID: 4407159e5749
Revises: b69b4737e7d5
Create Date: 2018-12-09 00:26:26.439056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4407159e5749'
down_revision = 'b69b4737e7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airline', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airline', 'slug')
    # ### end Alembic commands ###
