"""empty message

Revision ID: 5c02ccc1d8ac
Revises: 403dd57665d2
Create Date: 2018-12-09 16:10:36.166075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c02ccc1d8ac'
down_revision = '403dd57665d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsa_flight', sa.Column('coach_class', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gsa_flight', 'coach_class')
    # ### end Alembic commands ###
