"""empty message

Revision ID: 87efb2c24729
Revises: 122d89b5422f
Create Date: 2018-12-08 22:14:19.694079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87efb2c24729'
down_revision = '122d89b5422f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_country_id_fkey', 'city', type_='foreignkey')
    op.drop_column('city', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('city_country_id_fkey', 'city', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###
