"""empty message

Revision ID: c5bbf03e3f10
Revises: 38103c03dbe1
Create Date: 2018-12-09 13:57:41.692082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bbf03e3f10'
down_revision = '38103c03dbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsa_flight', sa.Column('airline_id', sa.Integer(), nullable=False))
    op.add_column('gsa_flight', sa.Column('destination_id', sa.Integer(), nullable=False))
    op.add_column('gsa_flight', sa.Column('fare_type', sa.String(length=255), nullable=True))
    op.add_column('gsa_flight', sa.Column('flight_class', sa.String(length=255), nullable=True))
    op.add_column('gsa_flight', sa.Column('invoice', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('gsa_flight', sa.Column('online', sa.Boolean(), nullable=True))
    op.add_column('gsa_flight', sa.Column('origin_id', sa.Integer(), nullable=False))
    op.add_column('gsa_flight', sa.Column('reservation_date', sa.Date(), nullable=True))
    op.add_column('gsa_flight', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('gsa_flight', sa.Column('trip_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'gsa_flight', 'airport', ['origin_id'], ['id'])
    op.create_foreign_key(None, 'gsa_flight', 'airline', ['airline_id'], ['id'])
    op.create_foreign_key(None, 'gsa_flight', 'airport', ['destination_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gsa_flight', type_='foreignkey')
    op.drop_constraint(None, 'gsa_flight', type_='foreignkey')
    op.drop_constraint(None, 'gsa_flight', type_='foreignkey')
    op.drop_column('gsa_flight', 'trip_date')
    op.drop_column('gsa_flight', 'tax')
    op.drop_column('gsa_flight', 'reservation_date')
    op.drop_column('gsa_flight', 'origin_id')
    op.drop_column('gsa_flight', 'online')
    op.drop_column('gsa_flight', 'invoice')
    op.drop_column('gsa_flight', 'flight_class')
    op.drop_column('gsa_flight', 'fare_type')
    op.drop_column('gsa_flight', 'destination_id')
    op.drop_column('gsa_flight', 'airline_id')
    # ### end Alembic commands ###
