"""empty message

Revision ID: c99dd5cc3d61
Revises: 5c02ccc1d8ac
Create Date: 2018-12-09 16:16:18.313935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99dd5cc3d61'
down_revision = '5c02ccc1d8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gsa_flight', 'flight_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsa_flight', sa.Column('flight_class', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
