"""empty message

Revision ID: d305b996569f
Revises: 4407159e5749
Create Date: 2018-12-09 12:27:54.304329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd305b996569f'
down_revision = '4407159e5749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsa_flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=True),
    sa.Column('trip_date', sa.Date(), nullable=True),
    sa.Column('flightclass', sa.String(length=255), nullable=True),
    sa.Column('invoice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('fare_type', sa.String(length=255), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['airport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gsa_flight')
    # ### end Alembic commands ###
