"""empty message

Revision ID: e3462d62f361
Revises: 36944ba86c55
Create Date: 2018-12-08 23:12:06.786993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3462d62f361'
down_revision = '36944ba86c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airport', sa.Column('alias', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airport', 'alias')
    # ### end Alembic commands ###
