"""empty message

Revision ID: f004af0e2654
Revises: d305b996569f
Create Date: 2018-12-09 13:40:47.795152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f004af0e2654'
down_revision = 'd305b996569f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsa_flight', sa.Column('flight_class', sa.String(length=255), nullable=True))
    op.drop_column('gsa_flight', 'flightclass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsa_flight', sa.Column('flightclass', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('gsa_flight', 'flight_class')
    # ### end Alembic commands ###
